services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: social-media-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mern
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-media-network

  # Backend Service
  backend:
    build: .
    container_name: social-media-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/mern
      - ACCESS_TOKEN_SECRET=itissecret
      - REFRESH_TOKEN_SECRET=itisalsosecret
      - PORT=8080
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - social-media-network

  # Frontend Service
  frontend:
    build: ./client
    container_name: social-media-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_IMAGE_UPLOAD_URL=http://localhost:8080/v1_1/social_media_app/image/upload
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - social-media-network

volumes:
  mongodb_data:

networks:
  social-media-network:
    driver: bridge
